---
name: Ansible Lint
on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

jobs:
  ansible-lint:
    name: Run Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml
      - name: Check yaml files
        uses: ansible/ansible-lint@v26.1.0
        with:
          args: "-c .ansible-lint"
